### ISSUE TITLE
DataSet Missing

### ISSUE THREAD

**Issue by Rmsharks4** [Ladvien/nn_learning_cnn_toxic_comment#1]

**Comment by Ladvien** [comment]
Hey @Rmsharks4,

The[ Kaggle rules](https://www.kaggle.com/c/jigsaw-toxic-comment-classification-challenge/rules) for this particular dataset state:
>Privately sharing code or data outside of teams is not permitted. It's okay to share code if made available to all participants on the forums.

But I do walk through getting the data here:
https://ladvien.com/deep-learning-natural-language-processing-toxic-comment-detector/

**Comment by Rmsharks4** [comment]
Yeah I got that after reading your tutorial. Thank you!

Regards,
Ramsha Siddiqui
